### ISSUE TITLE
Feature request - limit the amount of network communication with Casambi 

### ISSUE THREAD

**Issue by blannoy** [lkempf/casambi-bt#11]
It might useful to have a mode where no network is needed ( do a `casa.connect(device)` instead of `casa.connect(device,password)`). As far as I understand, if the unit info is stored (controls & keys), all the rest is direct BT communication. You would only need to connect once to get the necessary unit info and keys.

If you like I can look into that (I'm no real developer but I can write some code).

**Comment by lkempf** [comment]
I already implement caching for everything except the network config and the config is already versioned by the api. So to change this the network update must be refactored to actually use the config version and just leave it as is if there is no internet or the config is already the newest version. This could be done by simply saving the network config as $UUID.json and use the version stored within when talking to the api.

If you want to try implementing this feel free to. Otherwise I'll get around to do this eventually but I'm too busy at the moment.

**Comment by blannoy** [comment]
Added a proposal for a (simple) network cache. 
#12

**Comment by lkempf** [comment]
Just as a heads up: my master thesis was a lot more work than expected but this feature is planed for the next release sometimes around Easter

**Comment by lkempf** [comment]
I've added a `forceOffline` argument to `Casambi.connect` that can be used to prevent communication with the server.
